### PR TITLE
Added more info to most of the descriptions and changed the style to loo...

### PR DESCRIPTION
**Pull request by jeffsws**
...k similar to BG2 fixpack notes. /Flunders

### CODE REVIEW

**Comment by Sasha-alTherin** [comment]
I'm not going to use this as it totally messed up the formatting. I don't mind you adding in patch titles and adjusting the descriptions, but please keep the formatting.  If you need to indent more to make another level then do so. Patch titles should not be the same size as the component names themselves.  In fact they seem to be bigger.  Also the italic used in the original for the tph file name is carried all the way down the list.
If you would like to have a better title for the tph page, that's fine put it in and place the tph filename inside () immediately underneath.  Then indent and use normal bold text for specific patch titles with description following on next line, both with slightly smaller text size than the tph title was using.  Files altered/modified and/or created can be even smaller in text size.

**Comment by jeffsws** [comment]
When you say formatting do you mean style?  Or do you mean html format?

Can I add a colour to the title? Can I remove the "1), "2)" etc or is that what you mean by formatting?

Also what does span style="mso-list:Ignore" mean?

Cheers
Jeff

**Comment by Sasha-alTherin** [comment]
Also what does span style="mso-list:Ignore" mean?  <-- not sure to be honest.  it's what Microsoft Office used when I first did it with that program.  I think it meant to ignore the automatic bullets since I was telling it to remove them.  the style= could probably be removed.  will have to play with it i suppose.

When you say formatting do you mean style? Or do you mean html format?  <-- more html format.  style needs to be as close to regular readmes as possible, but i don't like have everything is listed straight down.  I prefer indenting to show that this stuff is underneath a specific topic etc...

Colors are fine, but patch titles should not draw more focus than the tph title OR the component titles themselves.

This is why I was concerned about having one long page.  I'm almost tempted to move the in depth tph file & patch descriptions to another page.  Thus formatting can then be more specific and not as concerned about how it fits with the rest of the readme.

The 1) & 2) stuff was used to signify distinct patches or group of  patches that did the same thing.

**Comment by jeffsws** [comment]
A question. I'm trying to set up the description so the entire description is indented and not just the first line.  The problem is there is a new line between the title and the description and yet I do not have any  "br /" so I’m slightly confused.

<p><strong><em>CUTSCENES-GorionSarevokVoiceOverlapFix.tph </em></strong><br />
<span style="color:#0000ff">Gorion And Serevok Voice Overlap</span>
<div style="margin-left:20px">
Gives a slight pause between two voice files that wereoverlapping during the
first encounter with Serevok after you first leave Candlekeep with Gorion.</div><br />
<span style="mso-list:Ignore"><span>       </span></span>Files modified are:<br />
<em><samp>ch1cut03.bcs</samp> </em> <br /></p>


EDIT: Can you see the code? It seems to have automatically run it.
EDIT 2: If I remove the < p  /p > then it works fine.  So I guess the div style conflicts with it? 
EDIT 3: This isn't the final code: I will keep the formatting :P I'm just testing right now.

**Comment by Sasha-alTherin** [comment]
div style="margin-left:20px  <-- i don't know what that is trying to do.  I did my indents by using the span and putting in the code for space, as many spaces as I wanted it to shift.  Look at what is used for the line "Files modified are:"  Copy that to use for each line instead.   just adjust the amount of spaces for it to span.

**Comment by jeffsws** [comment]
It indents the paragraph and not just the first line like the method you are using.  I was unable to edit the htm file again so I'll just post here one example.  Don't judge it based on what you see here. (the indents don't show here) Put it in the readme and see what you think.

<p><strong><em>
CUTSCENES-GorionSarevokVoiceOverlapFix.tph
  </em></strong><br />
  <span style="color:#0209fd">Gorion And Serevok Voice Overlap</span>
<p style="margin-left:20px">
Gives a slight pause between two voice files that were overlapping during the first encounter with Serevok after you first leave Candlekeep with Gorion.</p>

<p style="margin-left:20px">
Files modified are:  
  <em>
  <samp>
ch1cut03.bcs
  </samp>
  </em>
  <br />
  </p>

  </p>

**Comment by Sasha-alTherin** [comment]
that's better but what are you going to do when you have a long list of several patches within one tph file that needs to be explained differently.  This is why I had the 1), 2), etc..

**Comment by jeffsws** [comment]
Like so:  The titles replace the numbers and the fact they are blue helps show they belong to the one tph file.  I think :P

And again, looking here will not show you in its full glory :P

  <p><strong><em>
CUTSCENES-GorionSarevokVoiceOverlapFix.tph
  </em></strong><br />
  <span style="color:#0209fd">Gorion And Serevok Voice Overlap</span><p style="margin-left:20px">
Gives a slight pause between two voice files that were overlapping during the first encounter with Serevok after you first leave Candlekeep with Gorion.</p>

<p style="margin-left:20px">
Files modified are:  
  <em>
  <samp>
ch1cut03.bcs
  </samp>
  </em>
  </p>

  </p>

  <p><br /><strong><em>
  MUSIC-MusicFixesAllAndSagaOnly.tph
  </em></strong><br />
  <span style="color:#0209fd">Musiclist Filename Errors (Dudley)</span><p style="margin-left:20px">
  Contain some errors. Idobek explains: "If you load up BG:TotSC in DLTCEP you get (among other things) the following loading information: Generating music list... BD1 Missing music (BC1 B1) in musiclist. BL1 Missing music (BC1 B1) in musiclist. Upon investigating (i.e. goto 'Edit' 'Musiclist' and comparing these musiclists with others) it is easy to spot the problem: The last line of the 'loop suffix' section in of all other musiclists reads %FILENAME% %PARTSUFFIX% (i.e. BP2.mus reads 'BP2 A2'). BD1 and BL1 have 'BC1 B1' in the 'loop suffix' section. I simply changed 'BC1 B1' to the 'BD1 B1' and 'BL1 B1'. Oh, BC1 reads 'BC1 D1' so I have assumed the %PARTSUFFIX% part is correct.</p>
  <p style="margin-left:20px">
  Files modified are:
  <em>
  <samp>
  bd1.mus, bl1.mus
  </samp>
  </em>
  </p>
  <span style="color:#0209fd">3CD Original Saga Duplicate MUS Files (Dudley)</span><p style="margin-left:20px">
  A couple of respondents have noted that the 3CD Original Saga contains duplicate MUS files in certain instances. It is believed all MUS files should be unique.</p>
  <p style="margin-left:20px">
  Files modified are:
  <em>
  <samp>
  bc2.mus, bd1.mus, bd2.mus, bf2.mus, bl1.mus, bl2.mus, bp2.mus, cday2.mus, chants.mus, chapter.mus, dream.mus, dung2.mus, dung3.mus, tav2.mus, tav4.mus, tday2.mus
  </samp>
  </em>
  </p>
  </p>

**Comment by Sasha-alTherin** [comment]
With the component titles and other titles one color of blue, seeing that same color within descriptions draws more importance to it.  perhaps find another color, a darker blue perhaps?

**Pull request closed without merging**
